Don't display AppleScript notifications on macOS

diff --git a/assets/constructor_macOS.patch b/assets/constructor_macOS.patch
--- a/assets/constructor_macOS.patch
+++ b/assets/constructor_macOS.patch
@@ -1,5 +1,39 @@
---- lib/python3.9/site-packages/constructor/osxpkg.py	2022-02-09 14:17:06.000000000 +0100
-+++ /Users/hoechenberger/miniforge3/envs/constructor-fork/lib/python3.9/site-packages/constructor/osxpkg.py	2022-03-01 16:17:17.000000000 +0100
+diff -Naur constructor-orig/osx/post_extract.sh constructor-patched/osx/post_extract.sh
+--- constructor-orig/osx/post_extract.sh	2022-02-09 14:17:06.000000000 +0100
++++ constructor-patched/osx/post_extract.sh	2022-03-19 16:04:23.000000000 +0100
+@@ -24,7 +24,7 @@
+
+ # Extract the conda packages but avoiding the overwriting of the
+ # custom metadata we have already put in place
+-notify "Preparing packages..."
++logger -p 'install.info' "Preparing packages..."
+ "$CONDA_EXEC" constructor --prefix "$PREFIX" --extract-conda-pkgs
+ if (( $? )); then
+     echo "ERROR: could not extract the conda packages"
+@@ -32,7 +32,7 @@
+ fi
+
+ # Perform the conda install
+-notify "Installing packages. This might take a few minutes."
++logger -p 'install.info' "Installing packages. This might take a few minutes."
+ CONDA_SAFETY_CHECKS=disabled \
+ CONDA_EXTRA_SAFETY_CHECKS=no \
+ CONDA_CHANNELS=__CHANNELS__ \
+@@ -65,9 +65,9 @@
+
+
+ if [ -n '__SHORTCUTS__' ]; then
+-    notify "Done! You can open __NAME__ via ~/Applications."
++    logger -p 'install.info' "Done! You can find __NAME__ in the Applications folder."
+ else
+-    notify "Done! Installation is available in $PREFIX."
++    logger -p 'install.info' "Done! Installation is available in $PREFIX."
+ fi
+
+ echo "installation to $PREFIX finished."
+diff -Naur constructor-orig/osxpkg.py constructor-patched/osxpkg.py
+--- constructor-orig/osxpkg.py	2022-02-09 14:17:06.000000000 +0100
++++ constructor-patched/osxpkg.py	2022-03-01 16:17:17.000000000 +0100
 @@ -153,8 +153,11 @@
      # See below for an explanation of the consequences of this
      # customLocation value.
@@ -11,7 +45,7 @@
 +        options.set('rootVolumeOnly', 'true')
 +        # Force to run installer through Rosetta 2 on Apple Silicon
 +        options.set('hostArchitectures', 'x86_64')
- 
+
      # By default, the package builder puts all of our options under
      # a single master choice. This deletes that master choice and
 @@ -215,10 +218,11 @@
@@ -28,8 +62,8 @@
 +    #                      enable_currentUserHome='false')
 +    # root.append(domains)
      tree.write(xml_path)
- 
- 
+
+
 @@ -258,6 +262,7 @@
      args = [
          "pkgbuild",
@@ -37,4 +71,4 @@
 +        "--install-location=/Applications/MNE-Python",
          "--identifier", "%s.pkg.%s" % (identifier, name),
          "--ownership", "preserve",
- 
+
